#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: class-app
  labels:
    app: class-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: class-app
  template:
    metadata:
      labels:
        app: class-app
    spec:
      containers:
      - name: customcontainer
        image: neyo101/project250k:project250k
        ports:
        - containerPort: 8080

